<?php

function simple_calc_menu() {
  $items = array();

  $items['simple_calc'] = array(
    'title' => 'Simple calc',
    'description' => 'Simple calc test page',
    'page callback' => '', // Missing
    'access arguments' => array(), // Missing
  );

  return $items;
}

function simple_calc_permission() {
  return array(
    'use simple calc' => array(
      'title' => t('Use the simple calculator'),
    ),
  );
}

function simple_calc_form() {
  $form = array();

  $form['int1'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#default_value' => '',
  );

  $form['operator'] = array(
    '#type' => 'select',
    '#options' => array(
      'add' => '+',
      // Missing, add other operators
      ),
  );

  
  $form['int2'] = array();
  // Missing.

  $form['calculate'] = array(
    '#type' => 'submit',
    '#value' => 'Calculate',
  );
  return $form;
}

function simple_calc_page() {
  return drupal_get_form('simple_calc_form');
}

function simple_calc_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];
  // Missing, generate the $answer variable
  drupal_set_message("The Answer is " + $answer);
}

function simple_calc_calculate($int1, $int2, $operator) {
  // Missing, build this function.
  
}

